Web/Models/Candidat.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsForCoders.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidat
    {
        public Candidat()
        {
            this.Applications = new HashSet<Application>();
            this.Entreprises = new HashSet<Entreprise>();
        }
    
        public int JobSeekerID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public System.DateTime Birthdate { get; set; }
        public string Gender { get; set; }
        public string Education { get; set; }
        public string Objectives { get; set; }

        public string Introduction { get; set; }
        public string Links { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Cellphone { get; set; }
        public string Buzz_Words { get; set; }
        public string Operator { get; set; }
        public string Photo1 { get; set; }
        public string CV { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
    
        public virtual ICollection<Application> Applications { get; set; }
        public virtual ICollection<Entreprise> Entreprises { get; set; }
    }
}

Web/Controllers/CandidatsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JobsForCoders.Models;
using System.Net.Mail;
using System.IO;
using System.Threading.Tasks;
using WebGrease.Activities;

namespace JobsForCoders.Controllers
{
    public class CandidatsController : Controller
    {
        private jobsforcodersEntities db = new jobsforcodersEntities();

        // GET: JobSeekers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Candidat jobSeeker = db.Candidats.Find(id);
            if (jobSeeker == null)
            {
                return HttpNotFound();
            }
            return View(jobSeeker);
        }






    

        // GET: JobSeekers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: JobSeekers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "JobSeekerID,Name,Surname,Birthdate,Gender,Address,City,Education,Objectives,Introduction,Links,Email,Password,Cellphone,Operator,Buzz_Words")] Candidat jobSeeker, HttpPostedFileBase Photo1, HttpPostedFileBase CV)
        {
            if (ModelState.IsValid)
            {
                if (CV != null && CV.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(CV.FileName);
                    var path = Path.Combine(Server.MapPath("~/Uploads/"), fileName);
                    CV.SaveAs(path);

                    jobSeeker.CV = fileName;
                }

                if (Photo1 != null && Photo1.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(Photo1.FileName);
                    var path = Path.Combine(Server.MapPath("~/Uploads/"), fileName);
                    Photo1.SaveAs(path);

                    jobSeeker.Photo1 = fileName;
                }


                db.Candidats.Add(jobSeeker);
                db.SaveChanges();


                //Determine the Cellphone Operator
                var operatorValue = jobSeeker.Operator;
                if (operatorValue == "Virgin")
                {
                    jobSeeker.Cellphone = jobSeeker.Cellphone + "@vmobile.ca";
                }
                if (operatorValue == "Fido" || operatorValue == "Microcell")
                {
                    jobSeeker.Cellphone = jobSeeker.Cellphone + "@fido.ca";
                }
                if (operatorValue == "Rogers")
                {
                    jobSeeker.Cellphone = jobSeeker.Cellphone + "@fido.ca";
                }
                if (operatorValue == "Bell")
                {
                    jobSeeker.Cellphone = jobSeeker.Cellphone + "@txt.bell.ca";
                }
                if (operatorValue == "Telus")
                {
                    jobSeeker.Cellphone = jobSeeker.Cellphone + "@msg.telus.ca";
                }





                //Email
                //var body = "<p>Email From: {0} ({1})</p><p>Message:</p><p>{2}</p>";
                //var message = new MailMessage();
                //message.To.Add(new MailAddress(jobSeeker.Email));  // replace with valid value 
                //message.From = new MailAddress("jobforcoders@hotmail.com");  // replace with valid value
                //message.Subject = "Welcome to #JobForCoders!";
                //message.Body = string.Format(body, "JobForCoders", "no-reply@jobforcoders.com", "Registration completed.");
                //message.IsBodyHtml = true;

                //using (var smtp = new SmtpClient())
                //{
                //    var credential = new NetworkCredential
                //    {
                //        UserName = "jobforcoders@hotmail.com",  // replace with valid value
                //        Password = "555555Jc"  // replace with valid value
                //    };
                //    smtp.Credentials = credential;
                //    smtp.Host = "smtp-mail.outlook.com";
                //    smtp.Port = 587;
                //    smtp.EnableSsl = true;
                //    await smtp.SendMailAsync(message);
                //}


                ////SMS
                //var tbody = "<p>Email From: {0} ({1})</p><p>Message:</p><p>{2}</p>";
                //var tmessage = new MailMessage();
                //tmessage.To.Add(new MailAddress(jobSeeker.Cellphone));  // replace with valid value 
                //tmessage.From = new MailAddress("jobforcoders@hotmail.com");  // replace with valid value
                //tmessage.Subject = "Welcome to #JobForCoders!";
                //tmessage.Body = string.Format(tbody, "JobForCoders", "no-reply@jobforcoders.com", "Registration completed.");
                //tmessage.IsBodyHtml = true;

                //using (var smtp = new SmtpClient())
                //{
                //    var credential = new NetworkCredential
                //    {
                //        UserName = "jobforcoders@hotmail.com",  // replace with valid value
                //        Password = "555555Jc"  // replace with valid value
                //    };
                //    smtp.Credentials = credential;
                //    smtp.Host = "smtp-mail.outlook.com";
                //    smtp.Port = 587;
                //    smtp.EnableSsl = true;
                //    await smtp.SendMailAsync(tmessage);
                //}


                //This will load all Employers where the Buzz_Words contains jobseekers Buzz_Words

                var buzzWords = jobSeeker.Buzz_Words.Split(',').ToList();
                //var EmployerList = db.Entreprises.Where(e => e.Buzz_Words.Contains(jobSeeker.Buzz_Words));


                //foreach (var employer in EmployerList)
                //{
                //    //Determine the Cellphone Operator
                //    var operatorValueRegister = employer.Operator;
                //    if (operatorValueRegister == "Virgin")
                //    {
                //        employer.Cellphone = employer.Cellphone + "@vmobile.ca";
                //    }
                //    if (operatorValueRegister == "Fido" || operatorValueRegister == "Microcell")
                //    {
                //        employer.Cellphone = employer.Cellphone + "@fido.ca";
                //    }
                //    if (operatorValueRegister == "Rogers")
                //    {
                //        employer.Cellphone = employer.Cellphone + "@fido.ca";
                //    }
                //    if (operatorValueRegister == "Bell")
                //    {
                //        employer.Cellphone = employer.Cellphone + "@txt.bell.ca";
                //    }
                //    if (operatorValueRegister == "Telus")
                //    {
                //        employer.Cellphone = employer.Cellphone + "@msg.telus.ca";
                //    }

                //    //Email
                //    var secondbody = "<p>Email From: {0} ({1})</p><p>Message:</p><p>{2}</p>";
                //    var secondmessage = new MailMessage();
                //    secondmessage.To.Add(new MailAddress(employer.Email));  // replace with valid value 
                //    secondmessage.From = new MailAddress("jobforcoders@hotmail.com");  // replace with valid value
                //    secondmessage.Subject = "News from #JobForCoders!";
                //    secondmessage.Body = string.Format(secondbody, "JobForCoders", "no-reply@jobforcoders.com", "A new interesting applicand has just registered.");
                //    secondmessage.IsBodyHtml = true;

                //    using (var smtp = new SmtpClient())
                //    {
                //        var credential = new NetworkCredential
                //        {
                //            UserName = "jobforcoders@hotmail.com",  // replace with valid value
                //            Password = "555555Jc"  // replace with valid value
                //        };
                //        smtp.Credentials = credential;
                //        smtp.Host = "smtp-mail.outlook.com";
                //        smtp.Port = 587;
                //        smtp.EnableSsl = true;
                //        await smtp.SendMailAsync(secondmessage);
                //    }


                //    //SMS
                //    var tsecondbody = "<p>Email From: {0} ({1})</p><p>Message:</p><p>{2}</p>";
                //    var tsecondmessage = new MailMessage();
                //    tsecondmessage.To.Add(new MailAddress(employer.Cellphone));  // replace with valid value 
                //    tsecondmessage.From = new MailAddress("jobforcoders@hotmail.com");  // replace with valid value
                //    tsecondmessage.Subject = "Welcome to #JobForCoders!";
                //    tsecondmessage.Body = string.Format(tsecondbody, "JobForCoders", "no-reply@jobforcoders.com", "A new interesting applicand has just registered.");
                //    tsecondmessage.IsBodyHtml = true;

                //    using (var smtp = new SmtpClient())
                //    {
                //        var credential = new NetworkCredential
                //        {
                //            UserName = "jobforcoders@hotmail.com",  // replace with valid value
                //            Password = "555555Jc"  // replace with valid value
                //        };
                //        smtp.Credentials = credential;
                //        smtp.Host = "smtp-mail.outlook.com";
                //        smtp.Port = 587;

Web/Views/Candidats/Create.cshtml
@model JobsForCoders.Models.Candidat

<h2>Register as JobSeeker</h2>

@using (Html.BeginForm("Create", "Candidats", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name)
                    @Html.ValidationMessageFor(model => model.Name)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Surname)
                    @Html.ValidationMessageFor(model => model.Surname)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Birthdate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Birthdate)
                    @Html.ValidationMessageFor(model => model.Birthdate)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Gender)
                    @Html.ValidationMessageFor(model => model.Gender)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Address)
                    @Html.ValidationMessageFor(model => model.Address)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.City)
                    @Html.ValidationMessageFor(model => model.City)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Education, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Education)
                    @Html.ValidationMessageFor(model => model.Education)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Objectives, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Objectives)
                    @Html.ValidationMessageFor(model => model.Objectives)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Introduction, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.Introduction)
                    @Html.ValidationMessageFor(model => model.Introduction)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Links, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Links)
                    @Html.ValidationMessageFor(model => model.Links)
                </div>
            </div>
        </div>
        <br />

        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email)
                    @Html.ValidationMessageFor(model => model.Email)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Password)
                    @Html.ValidationMessageFor(model => model.Password)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Cellphone, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Cellphone)
                    @Html.ValidationMessageFor(model => model.Cellphone)
                </div>
            </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Operator, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Operator)
                        @Html.ValidationMessageFor(model => model.Operator)
                    </div>
                </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Buzz_Words, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Buzz_Words)
                    @Html.ValidationMessageFor(model => model.Buzz_Words)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.CV, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="CV" />
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Photo1, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="Photo1" />
                </div>
            </div>
        
        </div>
       
        <div class="form-group">
            <div class="col-md-offset-2 col-md-12">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
      
    </div>
}

Web/Views/Candidats/Delete.cshtml
@model JobsForCoders.Models.Candidat

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>JobSeeker</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Surname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Birthdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Birthdate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Education)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Education)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Objectives)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Objectives)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Introduction)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Introduction)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Links)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Links)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Cellphone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Cellphone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Operator)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Operator)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Buzz_Words)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Buzz_Words)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CV)
        </dt>

        <dd>
            <a href="~/Uploads/@Html.DisplayFor(model => model.CV)" target="_blank">
                Download
            </a>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo1)
        </dt>

        <dd>
            <img src="~/Uploads/@Html.DisplayFor(model => model.Photo1)" alt="" class="img-small" />
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Photo2)
        </dt>

        <dd>
            <img src="~/Uploads/@Html.DisplayFor(model => model.Photo2)" alt="" class="img-small" />
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Photo3)
        </dt>

        <dd>
            <img src="~/Uploads/@Html.DisplayFor(model => model.Photo3)" alt="" class="img-small" />
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> 
        </div>
    }
</div>

Web/Views/Candidats/Details.cshtml
@model JobsForCoders.Models.Candidat

@{
    ViewBag.Title = "Details";
}


<div class="container">
    <div class="col-sm-8">
        <div class="bs-calltoaction bs-calltoaction-default">
            <div class="row">
                <div class="col-md-1 cta-contents">
                    <h1 class="cta-title"><img src="~/Uploads/@Html.DisplayFor(model => model.Photo1)" width="140" height="135"></h1>
                    <div class="cta-desc">

                        <a class="btn btn-primary btn-block" href="~/Uploads/@Html.DisplayFor(model => model.CV)" target="_blank">
                            Download CV
                        </a>
                    </div>
                </div>
                <div class="col-md-7 cta-button">
                    <h3>@Html.DisplayFor(model => model.Name) @Html.DisplayFor(model => model.Surname)</h3>
                    <p><strong> Birthdate :</strong> @Html.DisplayFor(model => model.Birthdate)</p>
                    <p><strong>Gender :</strong> @Html.DisplayFor(model => model.Gender)</p>
                    <p><strong>Introduction :</strong> @Html.DisplayFor(model => model.Introduction) </p>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="bs-calltoaction bs-calltoaction-default">
            <div class="row">
                <div class="col-md-12 cta-contents">
                    <h3 class="cta-title">
                        Following
                    </h3>
                 </div>

            </div>
@foreach (var item in Model.Entreprises)
{
            <div class="row">
                <div class="col-md-12 cta-contents">
                    <div class="thumbnail">
                        <img src="~/Uploads/@Html.DisplayFor(modelItem => item.Logo)" alt="advetiser logo">
                        <a href="" class="feature-link"><h3>@Html.DisplayFor(modelItem => item.Name)</h3></a>
                        <p>@Html.DisplayFor(modelItem => item.Website)</p>
                        <div class="feature-btns"> @Html.ActionLink("Details", "Details", new { id = item.EntrepriseID }, new { @class = "btn btn-primary" })</div>
                    </div>
                </div>

            </div>

}


        </div>
    </div>
</div>


<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.JobSeekerID }) |
</p>

Web/Views/Candidats/Edit.cshtml
@model JobsForCoders.Models.Candidat

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "JobSeekers", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>JobSeeker</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.JobSeekerID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Surname)
                @Html.ValidationMessageFor(model => model.Surname)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Birthdate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Birthdate)
                @Html.ValidationMessageFor(model => model.Birthdate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gender)
                @Html.ValidationMessageFor(model => model.Gender)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address)
                @Html.ValidationMessageFor(model => model.Address)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City)
                @Html.ValidationMessageFor(model => model.City)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Education, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Education)
                @Html.ValidationMessageFor(model => model.Education)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Objectives, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Objectives)
                @Html.ValidationMessageFor(model => model.Objectives)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Introduction, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.TextAreaFor(model => model.Introduction)
                @Html.ValidationMessageFor(model => model.Introduction)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Links, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Links)
                @Html.ValidationMessageFor(model => model.Links)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password)
                @Html.ValidationMessageFor(model => model.Password)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Cellphone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cellphone)
                @Html.ValidationMessageFor(model => model.Cellphone)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Operator, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Operator)
                @Html.ValidationMessageFor(model => model.Operator)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Buzz_Words, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Buzz_Words)
                @Html.ValidationMessageFor(model => model.Buzz_Words)
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Current CV file</label>
            <div class="col-md-10">
                <a href="~/Uploads/@Html.DisplayFor(model => model.CV)" target="_blank">
                    Download
                </a>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Change CV file</label>
            <div class="col-md-10">
                <input type="file" name="CV" />
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Current Photo1</label>
            <div class="col-md-10">
                <a href="~/Uploads/@Html.DisplayFor(model => model.Photo1)" target="_blank">
                    <img src="~/Uploads/@Html.DisplayFor(model => model.Photo1)" alt="" class="img-small" />
                </a>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Change Photo1 file</label>
            <div class="col-md-10">
                <input type="file" name="Photo1" />
            </div>
        </div>

      


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@Html.ActionLink("Delete Your Account", "Delete", new { id = Model.JobSeekerID })