Web/Controllers/EntreprisesController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JobsForCoders.Models;
using System.Threading.Tasks;
using System.Net.Mail;
using System.IO;
using WebGrease.Activities;

namespace JobsForCoders.Controllers
{
    public class EntreprisesController : Controller
    {
        private jobsforcodersEntities db = new jobsforcodersEntities();

        // GET: Entreprise/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Entreprise entreprise = db.Entreprises.Find(id);
            if (entreprise == null)
            {
                return HttpNotFound();
            }
            return View(entreprise);
        }

        // GET: Entreprise/Create
        public ActionResult Create()
        {
            return View();
        }

        public enum FileType
        {
            Avatar = 1, Photo
        }

        // POST: Entreprise/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "EntrepriseID,Name,Address,City,Email,Password,Cellphone,Website")] Entreprise entreprise, HttpPostedFileBase Logo)
        {
            if (ModelState.IsValid)
            {
                

                if (Logo != null && Logo.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(Logo.FileName);
                    var path = Path.Combine(Server.MapPath("~/Uploads/"), fileName);
                    Logo.SaveAs(path);

                    entreprise.Logo = fileName;
                }

                db.Entreprises.Add(entreprise);
                db.SaveChanges();

                ////Determine the Cellphone Operator
                //var operatorValue = entreprise.Operator;
                //if (operatorValue == "Virgin")
                //{
                //    entreprise.Cellphone = entreprise.Cellphone + "@vmobile.ca";
                //}
                //if (operatorValue == "Fido" || operatorValue == "Microcell")
                //{
                //    entreprise.Cellphone = entreprise.Cellphone + "@fido.ca";
                //}
                //if (operatorValue == "Rogers")
                //{
                //    entreprise.Cellphone = entreprise.Cellphone + "@fido.ca";
                //}
                //if (operatorValue == "Bell")
                //{
                //    entreprise.Cellphone = entreprise.Cellphone + "@txt.bell.ca";
                //}
                //if (operatorValue == "Telus")
                //{
                //    entreprise.Cellphone = entreprise.Cellphone + "@msg.telus.ca";
                //}

                ////Email
                //var body = "<p>Email From: {0} ({1})</p><p>Message:</p><p>{2}</p>";
                //var message = new MailMessage();
                //message.To.Add(new MailAddress(entreprise.Email));  // replace with valid value 
                //message.From = new MailAddress("jobforcoders@hotmail.com");  // replace with valid value
                //message.Subject = "Welcome to #JobForCoders!";
                //message.Body = string.Format(body, "JobForCoders", "no-reply@jobforcoders.com", "Registration completed.");
                //message.IsBodyHtml = true;

                //using (var smtp = new SmtpClient())
                //{
                //    var credential = new NetworkCredential
                //    {
                //        UserName = "jobforcoders@hotmail.com",  // replace with valid value
                //        Password = "555555Jc"  // replace with valid value
                //    };
                //    smtp.Credentials = credential;
                //    smtp.Host = "smtp-mail.outlook.com";
                //    smtp.Port = 587;
                //    smtp.EnableSsl = true;
                //    await smtp.SendMailAsync(message);
                //}

                ////SMS
                //var tbody = "<p>Email From: {0} ({1})</p><p>Message:</p><p>{2}</p>";
                //var tmessage = new MailMessage();
                //tmessage.To.Add(new MailAddress(entreprise.Cellphone));  // replace with valid value 
                //tmessage.From = new MailAddress("jobforcoders@hotmail.com");  // replace with valid value
                //tmessage.Subject = "Welcome to #JobForCoders!";
                //tmessage.Body = string.Format(tbody, "JobForCoders", "no-reply@jobforcoders.com", "Registration completed.");
                //tmessage.IsBodyHtml = true;

                //using (var smtp = new SmtpClient())
                //{
                //    var credential = new NetworkCredential
                //    {
                //        UserName = "jobforcoders@hotmail.com",  // replace with valid value
                //        Password = "555555Jc"  // replace with valid value
                //    };
                //    smtp.Credentials = credential;
                //    smtp.Host = "smtp-mail.outlook.com";
                //    smtp.Port = 587;
                //    smtp.EnableSsl = true;
                //    await smtp.SendMailAsync(tmessage);
                //}


                return RedirectToAction("EntrepriseLogin", "Home");
            }

            return View(entreprise);
        }

        // GET: Entreprise/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Entreprise entreprise = db.Entreprises.Find(id);
            if (entreprise == null)
            {
                return HttpNotFound();
            }
            return View(entreprise);
        }



        public ActionResult Follow(int? EntrepriseID)
        {
            var jobSeekerId = (int)Session["LoggedUserID"];

            var candidat = db.Candidats.Find(jobSeekerId);
            var entreprise = db.Entreprises.Find(EntrepriseID);
            candidat.Entreprises.Add(entreprise);
            entreprise.Candidats.Add(candidat);
            db.SaveChanges();

            return RedirectToAction("Index", "Home");

        }


        // POST: Entreprise/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EntrepriseID,Name,Address,City,Email,Password,Cellphone,Website")] Entreprise entreprise, HttpPostedFileBase Logo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(entreprise).State = EntityState.Modified;


                if (Logo != null && Logo.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(Logo.FileName);
                    var path = Path.Combine(Server.MapPath("~/Uploads/"), fileName);
                    Logo.SaveAs(path);

                    entreprise.Logo = fileName;
                }
                else
                {
                    db.Entry(entreprise).Property(m => m.Logo).IsModified = false;
                }

                ModelState.Clear();

                db.SaveChanges();

                return RedirectToAction("Index", "Home");
            }
            return View(entreprise);


        }



        // GET: Entreprise/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Entreprise entreprise = db.Entreprises.Find(id);
            if (entreprise == null)
            {
                return HttpNotFound();
            }
            return View(entreprise);
        }

        // POST: Entreprise/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Entreprise entreprise = db.Entreprises.Find(id);
            db.Entreprises.Remove(entreprise);
            db.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Web/Controllers/ReportsJobSeekerController.cs
using JobsForCoders.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Text;

namespace JobsForCoders.Controllers
{
    public class ReportsJobSeekerController : Controller
    {
        private jobsforcodersEntities db = new jobsforcodersEntities();

        // GET: Reports
        public ActionResult Index()
        {
            return View();
        }

    /*    public ActionResult Export(Report report)
        {
            if (report.ExportTo == "pdf")
            {
                return ExportToPdf(report);
            }

            return ExportToWord(report);
        }*/

        public ActionResult Report(Report report)
        {
            Report jobSeekerReport = GenerateDataReport(report);

            return View(jobSeekerReport);
        }

        public Report GenerateDataReport(Report report)
        {
            //This is the Method to grab the data.
            var jobSeekerId = (int)Session["LoggedUserID"];

            var jobSeeker = db.Candidats.FirstOrDefault(js => js.JobSeekerID == jobSeekerId);

            var jobApplicationsQuery = db.Applications
                .Include(a => a.Offre)
                .Include(a => a.Offre.Entreprise)
                .Where(a => a.JobSeekerID == jobSeekerId);
            
            if(report.EmployerName != null)
            {
                jobApplicationsQuery = jobApplicationsQuery.Where(a => a.Offre.Entreprise.Name.Contains(report.EmployerName));
            }
            if (report.Position != null)
            {
                jobApplicationsQuery = jobApplicationsQuery.Where(a => a.Offre.Position.Contains(report.Position));
            }
            if(report.DateFrom > DateTime.MinValue)
            {
                jobApplicationsQuery = jobApplicationsQuery.Where(a => a.Application_Date >= report.DateFrom);
            }
            if (report.DateTo > DateTime.MinValue)
            {
                jobApplicationsQuery = jobApplicationsQuery.Where(a => a.Application_Date <= report.DateTo);
            }
            var jobApplications = jobApplicationsQuery.ToList();             

            var reportData = new Report()
            {
                Applications = jobApplications,
                JobSeeker = jobSeeker,
                DateFrom = report.DateFrom,
                DateTo = report.DateTo
            };
            return reportData;
        }


        //PDF and Word Generator
        public string RenderViewToString(string viewName, object model)
        {
            if (string.IsNullOrEmpty(viewName))
                viewName = ControllerContext.RouteData.GetRequiredString("action");

            ViewData.Model = model;

            using (var sw = new StringWriter())
            {
                var viewResult = ViewEngines.Engines.FindPartialView(ControllerContext, viewName);
                var viewContext = new ViewContext(ControllerContext, viewResult.View, ViewData, TempData, sw);
                viewResult.View.Render(viewContext, sw);
                return sw.GetStringBuilder().ToString();
            }
        }

  /*      public ActionResult ExportToPdf(Report report)
        {
            var htmlToConvert = RenderViewToString("Report", GenerateDataReport(report));
            var htmlToPdfConverter = new NReco.PdfGenerator.HtmlToPdfConverter();
            htmlToPdfConverter.PdfToolPath = Server.MapPath("~/Uploads/Reports/");
            var pdfBytes = htmlToPdfConverter.GeneratePdf(htmlToConvert);
            FileResult fileResult = new FileContentResult(pdfBytes, "application/pdf");
            fileResult.FileDownloadName = "Report.pdf";
            return fileResult;
        }

        public ActionResult ExportToWord(Report report)
        {
            var htmlToConvert = RenderViewToString("Report", GenerateDataReport(report));
            new List<string>().Add(htmlToConvert);
            HttpContext.Response.Clear();
            HttpContext.Response.Charset = "utf-8";
            HttpContext.Response.ContentType = "application/msword";
            const string strFileName = "Report.doc";
            HttpContext.Response.AddHeader("Content-Disposition", "inline;filename=" + strFileName);
            var strHtmlContent = new StringBuilder();
            strHtmlContent.Append(htmlToConvert);

            HttpContext.Response.Write(strHtmlContent);

            HttpContext.Response.End();
            HttpContext.Response.Flush();

            return null;

        }*/
    }
}

Web/Views/Entreprises/Create.cshtml
@model JobsForCoders.Models.Entreprise

<h2>Register as Entreprise</h2>

@using (Html.BeginForm("Create", "Entreprises", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address)
                @Html.ValidationMessageFor(model => model.Address)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City)
                @Html.ValidationMessageFor(model => model.City)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password)
                @Html.ValidationMessageFor(model => model.Password)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cellphone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cellphone)
                @Html.ValidationMessageFor(model => model.Cellphone)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Website, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Website)
                @Html.ValidationMessageFor(model => model.Website)
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Buzz_Words, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Buzz_Words)
                @Html.ValidationMessageFor(model => model.Buzz_Words)
            </div>
        </div>*@


        <div class="form-group">
            @Html.LabelFor(model => model.Logo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="Logo" />
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

Web/Views/Entreprises/Delete.cshtml
@model JobsForCoders.Models.Entreprise

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Employer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cellphone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cellphone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Operator)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Operator)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Website)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Website)
        </dd>

     

       

        <dt>
            @Html.DisplayNameFor(model => model.Logo)
        </dt>

        <dd>
            <img src="~/Uploads/@Html.DisplayFor(model => model.Logo)" alt="" class="img-small" />
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" />
        </div>
    }
</div>

Web/Views/Entreprises/Details.cshtml
@model JobsForCoders.Models.Entreprise
@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Employer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cellphone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cellphone)
        </dd>

   
        <dd>
            @Html.DisplayFor(model => model.Website)
        </dd>

     
        <dt>
            @Html.DisplayNameFor(model => model.Logo)
        </dt>

        <dd>
            <img src="~/Uploads/@Html.DisplayFor(model => model.Logo)" alt="" class="img-small" />
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.EntrepriseID }) |
    @Html.ActionLink("Back to List", "Index") | @Html.ActionLink("Follow", "Follow", new { EntrepriseID = Model.EntrepriseID })

    |@Html.ActionLink("Reports", "Index", "ReportsJobSeeker")

</p>

Web/Views/Entreprises/Edit.cshtml
@model JobsForCoders.Models.Entreprise

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Entreprises", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Employer</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.EntrepriseID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address)
                @Html.ValidationMessageFor(model => model.Address)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City)
                @Html.ValidationMessageFor(model => model.City)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password)
                @Html.ValidationMessageFor(model => model.Password)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cellphone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cellphone)
                @Html.ValidationMessageFor(model => model.Cellphone)
            </div>
        </div>

      

        <div class="form-group">
            @Html.LabelFor(model => model.Website, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Website)
                @Html.ValidationMessageFor(model => model.Website)
            </div>
        </div>


      

        <div class="form-group">
            <label class="control-label col-md-2">Current Logo</label>
            <div class="col-md-10">
                <a href="~/Uploads/@Html.DisplayFor(model => model.Logo)" target="_blank">
                    <img src="~/Uploads/@Html.DisplayFor(model => model.Logo)" alt="" class="img-small" />
                </a>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Change Logo file</label>
            <div class="col-md-10">
                <input type="file" name="Logo" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@Html.ActionLink("Delete Your Account", "Delete", new { id = Model.EntrepriseID })

Web/Views/Entreprises/Follow.cshtml
@model IEnumerable<JobsForCoders.Models.Entreprise>

@{
    ViewBag.Title = "Follow";
}

<h2>Index</h2>

Web/Views/Entreprises/Index.cshtml
@model IEnumerable<JobsForCoders.Models.Entreprise>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Password)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cellphone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Website)
        </th>
      
     
        <th>
            @Html.DisplayNameFor(model => model.Logo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Password)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cellphone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Website)
        </td>
      
        <td>
            <img src="~/Uploads/@Html.DisplayFor(modelItem => item.Logo)" alt="" class="img-small" />            
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.EntrepriseID }) |
            @Html.ActionLink("Details", "Details", new { id=item.EntrepriseID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.EntrepriseID })
        </td>
    </tr>
}

</table>